title: My Blog
description: just a simple blog...
theme: just-the-docs

url: https://ziggoon.github.io/blog

logo: "/img/logo.png"

aux_links:
  github: https://github.com/ziggoon/blog

color_scheme: dark
