title: Security <3!
description: Just a simple cybersecurity blog...
theme: just-the-docs

url: https://ziggoon.github.io/blog

logo: "/assets/img/logo.jpg"

aux_links:
  Github: https://github.com/ziggoon/blog

color_scheme: dark

search_enabled: true
search:
  rel_url: false

callouts_level: quiet
callouts:
  highlight: 
    color: purple
